stages:
  - build
  - test
  - deploy

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build
  script:
    - flutter build bundle

test:
  stage: test
  script:
    - flutter test

deploy:
  stage: deploy
  script:
    - dpl --provider=heroku --app=virtualmed --api-key=9c962830-e71b-4709-9f1e-9b2d28b61f1d
  only:
    - master