stages:
  - build
  - test

build:
  stage: build
  script:
    - bundle install
    - flutter build appbundle
    - cd android
    - bundle exec fastlane android test

test:
  stage: test
  script:
    - flutter test