stages:
  - build
  - test
  - deploy

before_script:
  - ls
  - flutter pub get
  - flutter clean

build:
  stage: build
  script:
    - flutter build bundle

test:
  stage: test
  script:
    - flutter test

deploy:
  stage: deploy
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/apk/app-release.apk